name: build_JOGDF_linux64


on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        continue-on-error: true
        run: |
          sudo apt-get install openjdk-8-jre openjdk-8-jdk
          cmake --version
          #sudo apt update
          #sudo apt install build-essential libtool autoconf unzip wget
          #sudo apt remove --purge --auto-remove cmake

          #version=3.27
          #build=0
          ## don't modify from here
          #mkdir ~/temp
          #cd ~/temp
          #wget https://cmake.org/files/v$version/cmake-$version.$build.tar.gz
          #tar -xzvf cmake-$version.$build.tar.gz
          #cd cmake-$version.$build/

          #./bootstrap
          #make -j$(nproc)
          #sudo make install

          #cmake --version
      - name: build dependencies
        run: |
          sudo apt-get update
          echo Building ogdf
          cd ogdf
          sudo cmake .
          sudo make -j 1

          echo Building tmap
          cd ../tmap
          sudo cmake .
          # sudo make -j 1

          echo Building Java-tmap Interface
          cd ../src
          sudo cmake .
          sudo make -j 1
      
      - name: build jogdf
        run: |
          mkdir build
          cd build
          pwd
          sudo cmake .. 
          sudo make -j 1
          sudo cmake --build . --target install -j 1

      - name: Run Test
        # working-directory: api/build/test
        # run: ./CLPTest
        run: echo skipped

      - uses: actions/upload-artifact@v3
        with:
          name: Jogdf_linux64
          path: build/native
      
