name: run_all
on:
  workflow_dispatch
jobs:
  run_all:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3.1.0
      - name: Call Workflows
        run: |
          gh workflow run build_JOGDF_linux64.yml
          gh workflow run build_JOGDF_win64.yml
          gh workflow run build_JOGDF_macos64.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
